bases:
  - ../../base

commonLabels:
  env: Dev

namespace: nginx-dev

configMapGenerator:
- name: example-configmap-html-1
  files:
  - index.html

secretGenerator:
- name: example-secret-1
  files:
  - password.txt



